[workspace]

members = [
  "iroha",
  "iroha_client",
  "iroha_client_no_std",
  "iroha_client_cli",
  "iroha_crypto",
  "iroha_crypto_cli",
  "iroha_data_model",
  "iroha_dsl",
  "iroha_macro",
  "iroha_macro/iroha_derive",
  "iroha_network",
  "iroha_substrate/parachain",
  "iroha_substrate/parachain/runtime",
  "iroha_substrate/parachain/runtime/collator",
]
