version: "3.2"

services:
  dev:
    build: iroha_substrate
    container_name: node-template
#    image: paritytech/ci-linux:production
    working_dir: /var/www/iroha/iroha_substrate/substrate-node-template
    ports:
      - "9944:9944"
    environment:
      - CARGO_HOME=/var/www/iroha/.cargo
    volumes:
      - .:/var/www/iroha
#      - ./iroha_substrate/substrate-node-template:/var/www/node-template
      - type: bind
        source: ./.local
        target: /root/.local
    command: bash -c "cargo build --package node-template && ../../target/debug/node-template --dev --ws-external & cd ../.. && RUST_LOG=error cargo run --package iroha --bin" # iroha > /dev/null"
