version: "3.2"

services:
  dev:
    build: iroha_substrate
    container_name: iroha-bridge
    working_dir: /var/www/iroha/iroha_substrate/substrate-iroha-bridge-node
    ports:
      - "9944:9944"
    environment:
      - CARGO_HOME=/var/www/iroha/.cargo
    volumes:
      - .:/var/www/iroha
      - type: bind
        source: ./.local
        target: /root/.local
    command: bash -c "cargo build --package substrate-iroha-bridge-node && ../../target/debug/substrate-iroha-bridge-node --dev --ws-external & cd ../.. && RUST_LOG=error cargo run --package iroha --bin" # iroha > /dev/null"
  dev-manual:
    build:
      context: .
      dockerfile: iroha_substrate/manual.Dockerfile
    container_name: iroha-bridge-manual
    working_dir: /var/www/iroha
    ports:
      - "9944:9944"
      - "7878:7878"
      - "8888:8888"
      - "1337:1337"
    environment:
      - CARGO_HOME=/var/www/iroha/.cargo
    volumes:
      - .:/var/www/iroha
      - type: bind
        source: ./.local
        target: /root/.local
    command: bash iroha_substrate/substrate-iroha-bridge-node/scripts/run_tester.sh
  dev-bin:
    build:
      context: iroha_substrate
      dockerfile: bin.Dockerfile
    container_name: iroha-bridge-bin
    ports:
      - "9944:9944"
      - "7878:7878"
      - "8888:8888"
      - "1337:1337"
    volumes:
      - type: bind
        source: ./.local
        target: /root/.local
    command: bash -c "RUST_LOG=pallet_iroha_bridge=debug ./substrate-iroha-bridge-node --dev --ws-external & RUST_LOG=error ./iroha > /dev/null & sleep 10 && ./bridge-tester"
